### ISSUE TITLE
ATM crash

### ISSUE THREAD

**Issue by codejam1024** [notabadminer/UniversalCoinsMod#13]
---- Minecraft Crash Report ----
// Quite honestly, I wouldn't worry myself about that.

Time: 15-7-11 下午11:26
Description: Updating screen events

java.lang.ExceptionInInitializerError
	at universalcoins.tile.TileCardStation.debitAccount(TileCardStation.java:412)
	at universalcoins.tile.TileCardStation.fillCoinSlot(TileCardStation.java:370)
	at universalcoins.tile.TileCardStation.func_70298_a(TileCardStation.java:77)
	at net.minecraft.inventory.Slot.func_75209_a(Slot.java:93)
	at net.minecraft.inventory.Container.func_75144_a(SourceFile:232)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78753_a(PlayerControllerMP.java:419)
	at codechicken.nei.guihook.GuiContainerManager.handleSlotClick(GuiContainerManager.java:504)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146984_a(GuiContainer.java:638)
	at net.minecraft.client.gui.inventory.GuiContainer.public_func_146984_a(GuiContainer.java)
	at codechicken.nei.guihook.DefaultSlotClickHandler.callHandleMouseClick(DefaultSlotClickHandler.java)
	at codechicken.nei.guihook.DefaultSlotClickHandler.handleSlotClick(DefaultSlotClickHandler.java:17)
	at codechicken.nei.guihook.GuiContainerManager.handleMouseClick(GuiContainerManager.java:453)
	at net.minecraft.client.gui.inventory.GuiContainer.managerHandleMouseClick(GuiContainer.java)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:394)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NullPointerException
	at universalcoins.util.UniversalAccounts.<init>(UniversalAccounts.java:151)
	at universalcoins.util.UniversalAccounts.<clinit>(UniversalAccounts.java:9)
	... 27 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at universalcoins.tile.TileCardStation.debitAccount(TileCardStation.java:412)
	at universalcoins.tile.TileCardStation.fillCoinSlot(TileCardStation.java:370)
	at universalcoins.tile.TileCardStation.func_70298_a(TileCardStation.java:77)
	at net.minecraft.inventory.Slot.func_75209_a(Slot.java:93)
	at net.minecraft.inventory.Container.func_75144_a(SourceFile:232)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78753_a(PlayerControllerMP.java:419)
	at codechicken.nei.guihook.GuiContainerManager.handleSlotClick(GuiContainerManager.java:504)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146984_a(GuiContainer.java:638)
	at net.minecraft.client.gui.inventory.GuiContainer.public_func_146984_a(GuiContainer.java)
	at codechicken.nei.guihook.DefaultSlotClickHandler.callHandleMouseClick(DefaultSlotClickHandler.java)
	at codechicken.nei.guihook.DefaultSlotClickHandler.handleSlotClick(DefaultSlotClickHandler.java:17)
	at codechicken.nei.guihook.GuiContainerManager.handleMouseClick(GuiContainerManager.java:453)
	at net.minecraft.client.gui.inventory.GuiContainer.managerHandleMouseClick(GuiContainer.java)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:394)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)

-- Affected screen --
Details:
	Screen name: universalcoins.gui.CardStationGUI

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['jam1024'/137, l='MpServer', x=-73.95, y=70.62, z=190.02]]
	Chunk stats: MultiplayerChunkCache: 358, 358
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-102,65,198), Chunk: (at 10,4,6 in -7,12; contains blocks -112,0,192 to -97,255,207), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 265712 game time, 268405 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 47 total; [EntitySpider['蜘蛛'/405, l='MpServer', x=-28.48, y=43.35, z=201.29], EntitySkeleton['骷髅'/408, l='MpServer', x=-45.50, y=29.00, z=186.50], EntityCreeper['爬行者'/282, l='MpServer', x=-123.50, y=43.00, z=143.00], EntityCreeper['爬行者'/410, l='MpServer', x=-43.50, y=29.00, z=182.50], EntityCow['牛'/27, l='MpServer', x=-126.41, y=69.00, z=203.63], EntityCow['牛'/31, l='MpServer', x=-99.28, y=68.00, z=183.47], EntityZombie['僵尸'/287, l='MpServer', x=-70.50, y=40.00, z=199.50], EntitySkeleton['骷髅'/32, l='MpServer', x=-97.09, y=64.00, z=177.53], EntitySkeleton['骷髅'/35, l='MpServer', x=-75.69, y=64.00, z=175.16], EntityCreeper['爬行者'/36, l='MpServer', x=-88.78, y=64.00, z=170.84], EntitySkeleton['骷髅'/37, l='MpServer', x=-63.09, y=64.00, z=185.47], EntitySkeleton['骷髅'/38, l='MpServer', x=-53.91, y=64.00, z=169.50], EntitySkeleton['骷髅'/39, l='MpServer', x=-88.69, y=64.00, z=177.22], EntityCreeper['爬行者'/40, l='MpServer', x=-91.22, y=64.00, z=186.09], EntityCreeper['爬行者'/42, l='MpServer', x=-79.41, y=64.00, z=199.03], EntityCow['牛'/45, l='MpServer', x=-65.31, y=64.00, z=130.69], EntityZombie['僵尸'/46, l='MpServer', x=-88.00, y=64.00, z=176.31], EntityItemFrame['entity.ItemFrame.name'/48, l='MpServer', x=-70.06, y=69.50, z=184.50], EntityItemFrame['entity.ItemFrame.name'/49, l='MpServer', x=-70.06, y=69.50, z=183.50], EntityItemFrame['entity.ItemFrame.name'/50, l='MpServer', x=-70.06, y=69.50, z=191.50], EntityItemFrame['entity.ItemFrame.name'/51, l='MpServer', x=-65.06, y=69.50, z=190.50], EntityItem['item.item.rottenFlesh'/179, l='MpServer', x=-50.69, y=66.13, z=227.03], EntityItemFrame['entity.ItemFrame.name'/52, l='MpServer', x=-65.06, y=69.50, z=184.50], EntityItemFrame['entity.ItemFrame.name'/53, l='MpServer', x=-67.94, y=69.50, z=191.50], EntityItemFrame['entity.ItemFrame.name'/54, l='MpServer', x=-67.94, y=69.50, z=183.50], EntityItemFrame['entity.ItemFrame.name'/55, l='MpServer', x=-67.94, y=69.50, z=182.50], EntityItemFrame['entity.ItemFrame.name'/56, l='MpServer', x=-67.94, y=69.50, z=184.50], EntitySkeleton['骷髅'/57, l='MpServer', x=-84.31, y=64.00, z=183.84], EntitySkeleton['骷髅'/58, l='MpServer', x=-64.92, y=64.00, z=169.50], EntityItemFrame['entity.ItemFrame.name'/59, l='MpServer', x=-70.06, y=69.50, z=192.50], EntityItemFrame['entity.ItemFrame.name'/60, l='MpServer', x=-67.94, y=69.50, z=193.50], EntityItemFrame['entity.ItemFrame.name'/61, l='MpServer', x=-67.94, y=69.50, z=192.50], EntityBat['蝙蝠'/189, l='MpServer', x=-13.38, y=36.98, z=174.25], EntitySkeleton['骷髅'/63, l='MpServer', x=-93.31, y=64.00, z=186.93], EntityZombie['僵尸'/66, l='MpServer', x=-53.69, y=64.00, z=174.09], EntityCreeper['爬行者'/75, l='MpServer', x=-77.28, y=64.00, z=181.16], EntityCreeper['爬行者'/76, l='MpServer', x=-93.30, y=64.00, z=172.97], EntitySquid['鱿鱼'/205, l='MpServer', x=-118.94, y=60.97, z=222.47], EntitySlime['史莱姆'/78, l='MpServer', x=-50.69, y=18.85, z=197.31], EntityCow['牛'/87, l='MpServer', x=-46.13, y=64.00, z=138.81], EntityCow['牛'/88, l='MpServer', x=-46.28, y=68.00, z=156.69], EntitySkeleton['骷髅'/372, l='MpServer', x=-16.50, y=41.00, z=225.50], EntitySkeleton['骷髅'/373, l='MpServer', x=-20.50, y=41.00, z=227.50], EntitySkeleton['骷髅'/374, l='MpServer', x=-15.91, y=41.00, z=224.50], EntitySkeleton['骷髅'/375, l='MpServer', x=-15.09, y=39.00, z=216.53], EntityClientPlayerMP['jam1024'/137, l='MpServer', x=-73.95, y=70.62, z=190.02], EntityWaypointContainer['未知'/14716, l='MpServer', x=0.00, y=0.00, z=0.00]]
	Retry entities: 0 total; []
	Server brand: kcauldron,cauldron,craftbukkit,mcpc,fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (x86) version 6.3
	Java Version: 1.8.0_45, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 167301904 bytes (159 MB) / 588701696 bytes (561 MB) up to 1037959168 bytes (989 MB)
	JVM Flags: 1 total; -Xmx1024m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 Optifine OptiFine_1.7.10_HD_U_C1 40 mods loaded, 40 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1448.jar) 
	UCHIJA	Forge{10.13.4.1448} [Minecraft Forge] (forge-1.7.10-10.13.4.1448.jar) 
	UCHIJA	CodeChickenCore{1.0.7.45} [CodeChicken Core] (minecraft.jar) 
	UCHIJA	InputFix{1.7.10-v5} [InputFix] (minecraft.jar) 
	UCHIJA	NotEnoughItems{1.0.5.110} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.110-universal.jar) 
	UCHIJA	uniskinmod{1.2-dev4} [Universal Skin Mod] (minecraft.jar) 
	UCHIJA	AppleCore{1.1.0} [AppleCore] (AppleCore-mc1.7.10-1.1.0.jar) 
	UCHIJA	Backpack{2.0.1} [Backpack] (backpack-2.0.1-1.7.x.jar) 
	UCHIJA	BetterFoliage{1.0.13} [Better Foliage] (BetterFoliage-mc1.7-1.0.13.jar) 
	UCHIJA	BuildCraft|Core{7.0.13} [BuildCraft] (buildcraft-7.0.13.jar) 
	UCHIJA	BuildCraft|Silicon{7.0.13} [BC Silicon] (buildcraft-7.0.13.jar) 
	UCHIJA	BuildCraft|Transport{7.0.13} [BC Transport] (buildcraft-7.0.13.jar) 
	UCHIJA	BuildCraft|Builders{7.0.13} [BC Builders] (buildcraft-7.0.13.jar) 
	UCHIJA	BuildCraft|Robotics{7.0.13} [BC Robotics] (buildcraft-7.0.13.jar) 
	UCHIJA	BuildCraft|Energy{7.0.13} [BC Energy] (buildcraft-7.0.13.jar) 
	UCHIJA	BuildCraft|Factory{7.0.13} [BC Factory] (buildcraft-7.0.13.jar) 
	UCHIJA	ChickenChunks{1.3.4.19} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.19-universal.jar) 
	UCHIJA	FastCraft{1.21} [FastCraft] (fastcraft-1.21.jar) 
	UCHIJA	IC2{2.2.747-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.747-experimental.jar) 
	UCHIJA	MemoryCleaner{1.0} [Memory Cleaner] (MemoryCleaner-1.4-mc.1.7.10.jar) 
	UCHIJA	mobends{0.20.1} [Mo' Bends] (MoBends-0.20.1 for MC 1.7.10.jar) 
	UCHIJA	MusicFix{0.2} [Music Fix] (MusicFix-0.2.jar) 
	UCHIJA	New Gui{1.0} [New Gui] (NewGui1.0.3-1.7.10.jar) 
	UCHIJA	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCHIJA	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) 
	UCHIJA	harvestcraft{1.7.10i} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10i.jar) 
	UCHIJA	SGCraft{1.9.3} [Greg's SG Craft] (SGCraft-1.9.3-mc1.7.10.jar) 
	UCHIJA	SpiceOfLife{1.2.3} [The Spice of Life] (SpiceOfLife-mc1.7.10-1.2.3.jar) 
	UCHIJA	thirstmod{1.8.14} [Thirst Mod] (thirstmod-1.8.14饮水[汉化].jar) 
	UCHIJA	UnicodeFontFixer{1.0.8} [UnicodeFontFixer] (UnicodeFontFixer-1.0.8-mc1.7.10.jar) 
	UCHIJA	universalcoins{1.7.10-1.6.23} [Universal Coins] (UniversalCoins-1.7.10-1.6.23.jar) 
	UCHIJA	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCHIJA	WailaHarvestability{1.1.0} [Waila Harvestability] (WailaHarvestability-mc1.7.x-1.1.0.jar) 
	UCHIJA	warpbook{2.0.null} [Warp Book] (warpbook-1.7.10_2.0.36.jar) 
	UCHIJA	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJA	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJA	HungerOverhaul{1.7.10-1.0.0.jenkins75} [Hunger Overhaul] (HungerOverhaul-1.7.10-1.0.0.jar) 
	UCHIJA	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.4.13084 Compatibility Profile Context 14.301.1001.0' Renderer: 'AMD Radeon HD 8330'
	Launched Version: Forge
	LWJGL: 2.9.1
	OpenGL: AMD Radeon HD 8330 GL version 4.4.13084 Compatibility Profile Context 14.301.1001.0, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: [Pixel Reality 1.7.10 UB.zip, Pixel Reality Atmosphere.zip, PR Addendum - Bright Stone.zip, PR Luminance - Full.zip]

**Comment by codejam1024** [comment]
Single player dones't  crash?

**Comment by notabadminer** [comment]
I went through all the code. The changes I made to the account handling were causing client side crashes. The 1.6.24 release should fix all the account handling issues. Leaving this open until the fix is verified.

**Comment by codejam1024** [comment]
work fine!

**Comment by notabadminer** [comment]
OK. I'll consider this issue resolved then.
