### ISSUE TITLE
Internal Server Error with Vending Blocks

### ISSUE THREAD

**Issue by ArmandVestibule** [notabadminer/UniversalCoinsMod#22]
(MC 1.7.10, UC 1.6.35)
This one seems a bit ambiguous, but here goes:

I crafted a stone based vending block, right-clicked to access the UI, and I noticed that it automatically filled most of the block's slots with items from my inventory. When i tried to manipulate those items to pull them back to my player inventory, I was disconnected from the server with an Internal Server Error.

Client output was nonexistent, but the server said:

java.lang.IndexOutOfBoundsException: Index: 46, Size: 41
	at java.util.ArrayList.rangeCheck(Unknown Source) ~[?:1.8.0_45]
	at java.util.ArrayList.get(Unknown Source) ~[?:1.8.0_45]
	at net.minecraft.inventory.Container.func_75144_a(SourceFile:206) ~[zs.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:883) ~[nh.class:?]
	at net.minecraft.network.play.client.C0EPacketClickWindow.func_148833_a(SourceFile:32) ~[ix.class:?]
	at net.minecraft.network.play.client.C0EPacketClickWindow.func_148833_a(SourceFile:10) ~[ix.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[10:24:37] [Server thread/INFO]: ##### lost connection: TextComponent{text='Internal server error', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null}}

When I tried to return to the game to destroy the vending block, it wouldn't let me. Only in creative mode could I finally destroy it.

Thanks!

**Comment by ArmandVestibule** [comment]
A secondary observation: After the error, it duped a handful of the items that it had auto-filled into the vending block.

**Comment by notabadminer** [comment]
It looks like a few variables were set wrong in the shift+click functions. The next release will have the fix.
