### ISSUE TITLE
World Corruption Bug

### ISSUE THREAD

**Issue by Cobra1117** [notabadminer/UniversalCoinsMod#28]
Placing an non-activated card (cheated in via NEI) into a vendor block causes this exception:
java.lang.NullPointerException: Ticking block entity
        at universalcoins.tile.TileVendor.getUserAccountBalance(TileVendor.java:1025)
        at universalcoins.tile.TileVendor.activateBuyButton(TileVendor.java:104)
        at universalcoins.tile.TileVendor.func_145845_h(TileVendor.java:90)
        at net.minecraft.world.World.func_72939_s(World.java:1939)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

This corrupts the world and causes it to be un-loadable.

**Comment by notabadminer** [comment]
This issue should be resolved with 1.7.x-1.6.38 release.
