### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by StarfireSky** [notabadminer/UniversalCoinsMod#48]
I downloaded the Universal Coins mod version 1.7.10-1.7.3 as soon as I loaded my minecraft game it crashed
---- Minecraft Crash Report ----
// Quite honestly, I wouldn't worry myself about that.

Time: 9/6/16 7:08 AM
Description: Initializing game

java.lang.NullPointerException: Initializing game
	at thehippomaster.aquaticabyss.AASpawnEgg.func_77653_i(AASpawnEgg.java:41)
	at net.minecraft.item.ItemStack.func_82833_r(ItemStack.java:427)
	at universalcoins.util.UCItemPricer.buildPricelistHashMap(UCItemPricer.java:133)
	at universalcoins.util.UCItemPricer.loadConfigs(UCItemPricer.java:57)
	at universalcoins.UniversalCoins.postInit(UniversalCoins.java:342)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:742)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at thehippomaster.aquaticabyss.AASpawnEgg.func_77653_i(AASpawnEgg.java:41)
	at net.minecraft.item.ItemStack.func_82833_r(ItemStack.java:427)
	at universalcoins.util.UCItemPricer.buildPricelistHashMap(UCItemPricer.java:133)
	at universalcoins.util.UCItemPricer.loadConfigs(UCItemPricer.java:57)
	at universalcoins.UniversalCoins.postInit(UniversalCoins.java:342)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:742)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1788772736 bytes (1705 MB) / 2840592384 bytes (2709 MB) up to 5726797824 bytes (5461 MB)
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6G
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 125 mods loaded, 125 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJ	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJ	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJ	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJ	AM2-Preloader{0.0.3} [AMCore] (minecraft.jar) 
	UCHIJ	MCVanillaTweaks{1.0} [Mariculture - Vanilla Tweaks] (minecraft.jar) 
	UCHIJ	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJ	AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI-1.7.10-1.2.4.jar) 
	UCHIJ	arsmagica2{1.4.0.009} [Ars Magica 2] (1.7.10_AM2-1.4.0.009.jar) 
	UCHIJ	jewelrycraft2{1.1.4} [Jewelrycraft 2] ([1.7.10] Jewelrycraft2-1.1.4-universal.jar) 
	UCHIJ	MCP_Wheel{1.1.2} [MC+ Wheel] ([1.7.10][1.2] MC+ Wheel - v1.1.2.jar) 
	UCHIJ	MCP_Cart{1.3.0} [MC+ Cart] ([1.7.10][1.2] MC+ Cart - v1.3.0.jar) 
	UCHIJ	MCP_Loom{1.2.3} [MC+ Loom] ([1.7.10][1.2] MC+ Loom - v1.2.3.jar) 
	UCHIJ	MCP_Turtle{1.2.3} [MC+ Turtle] ([1.7.10][1.2] MC+ Turtle - v1.2.3.jar) 
	UCHIJ	bspkrsCore{6.16} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.16.jar) 
	UCHIJ	Treecapitator{1.7.10} [Treecapitator] ([1.7.10]Treecapitator-universal-2.0.4.jar) 
	UCHIJ	njaymod_4{1.3} [NJay's Unicorn Mod] ([1.7.x] NJays Unicorn Mod (v1.3).jar) 
	UCHIJ	alluwant{2.1} [All U Want] (All-U-Want 2.1.jar) 
	UCHIJ	aquaticabyss{1.1.1} [Aquatic Abyss] (AquaticAbyss-1.7.10-1.1.1.jar) 
	UCHIJ	MovingWorld{1.7.10-1.8.1} [Moving World] (movingworld-1.7.10-1.8.1.jar) 
	UCHIJ	ArchimedesShipsPlus{1.7.10-1.8.1} [Archimedes' Ships Plus] (archimedesshipsplus-1.7.10-1.8.1.jar) 
	UCHIJ	Backpack{2.0.1} [Backpack] (backpack-2.0.1-1.7.x.jar) 
	UCHIJ	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCHIJ	betterstorage{0.13.1.127} [BetterStorage] (BetterStorage-1.7.10-0.13.1.127.jar) 
	UCHIJ	BiblioCraft{1.11.5} [BiblioCraft] (BiblioCraft[v1.11.5][MC1.7.10].jar) 
	UCHIJ	Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (Mantle-1.7.10-0.3.2b.jar) 
	UCHIJ	Natura{2.2.0} [Natura] (natura-1.7.10-2.2.0.1.jar) 
	UCHIJ	CoFHCore{1.7.10R3.1.2} [CoFH Core] (CoFHCore-[1.7.10]3.1.2-325.jar) 
	UCHIJ	Forestry{4.2.14.62} [Forestry for Minecraft] (forestry_1.7.10-4.2.14.62.jar) 
	UCHIJ	BiblioWoodsForestry{1.7} [BiblioWoods Forestry Edition] (BiblioWoods[Forestry][v1.7].jar) 
	UCHIJ	BiblioWoodsNatura{1.5} [BiblioWoods Natura Edition] (BiblioWoods[Natura][v1.5].jar) 
	UCHIJ	blocklings{3.0.3} [Blocklings] (Blocklings-3.0.3-1.7.10.jar) 
	UCHIJ	Botania{r1.8-249} [Botania] (Botania r1.8-249.jar) 
	UCHIJ	candycraftmod{Beta 1.3} [CandyCraft] (CandyCraft-1.3.jar) 
	UCHIJ	TwilightForest{2.3.7} [The Twilight Forest] (twilightforest-1.7.10-2.3.7.jar) 
	UCHIJ	chisel{2.9.5.11} [Chisel] (Chisel-2.9.5.11.jar) 
	UCHIJ	CarpentersBlocks{3.3.8_dev_r8} [Carpenter's Blocks] (Carpenter's Blocks v3.3.8_dev_r8 - MC 1.7.10.jar) 
	UCHIJ	chococraft{4.1.5} [Clienthax's ChocoCraft] (ChocoCraft-4.1.5.jar) 
	UCHIJ	BuildMod{v1.0} [Build Mod] (coroutil-1.1.3 for MC v1.7.10.jar) 
	UCHIJ	CoroPets{v1.0} [CoroPets] (coroutil-1.1.3 for MC v1.7.10.jar) 
	UCHIJ	CoroAI{v1.0} [CoroAI] (coroutil-1.1.3 for MC v1.7.10.jar) 
	UCHIJ	ExtendedRenderer{v1.0} [Extended Renderer] (coroutil-1.1.3 for MC v1.7.10.jar) 
	UCHIJ	ConfigMod{v1.0} [Extended Mod Config] (coroutil-1.1.3 for MC v1.7.10.jar) 
	UCHIJ	CraftHeraldry{1.1.3} [CraftHeraldry] (CraftHeraldry 1.1.3.jar) 
	UCHIJ	CustomSpawner{3.3.0} [DrZhark's CustomSpawner] (CustomMobSpawner 3.3.0.zip) 
	UCHIJ	customnpcs{1.7.10d} [CustomNpcs] (CustomNPCs_1.7.10d(21feb16).jar) 
	UCHIJ	PTRModelLib{1.0.0} [PTRModelLib] (Decocraft-2.3.3_1.7.10.jar) 
	UCHIJ	props{2.3.3} [Decocraft] (Decocraft-2.3.3_1.7.10.jar) 
	UCHIJ	doggytalents{v1.9.0h} [Doggy Talents] (DoggyTalents-1.7.10-v1.9.0h-universal.jar) 
	UCHIJ	DragonMounts{r41-1.7.10} [Dragon Mounts] (DragonMounts-r41-1.7.10.jar) 
	UCHIJ	MoCreatures{6.3.1} [DrZhark's Mo'Creatures Mod] (DrZharks MoCreatures Mod v6.3.1.zip) 
	UCHIJ	Enchiridion{1.1} [Enchiridion] (Enchiridion-1.7.X-1.2b.jar) 
	UCHIJ	enhancedportals{3.0.12} [EnhancedPortals] (EnhancedPortals_1.7.10-universal-3.0.12.jar) 
	UCHIJ	eureka{3.0.2} [Eureka] (Eureka-1.7.10-3.0.2.jar) 
	UCHIJ	exoticbirds{1.0} [Exotic Birds] (Exotic Birds 1.7.10 - 1.0.3b.jar) 
	UCHIJ	FairyFactions{0.5.2a} [Fairy Factions] (fairy-factions-1.7-0.5.2a.jar) 
	UCHIJ	fairylights{1.4.0} [Fairy Lights] (fairylights-1.4.0-1.7.10.jar) 
	UCHIJ	FlightlessDragon{1.0.4} [FlightlessDragon] (Flightless Dragon 1.0.4.zip) 
	UCHIJ	llibrary{1.5.1} [LLibrary] (llibrary-1.5.1-1.7.10.jar) 
	UCHIJ	fossil{7.3.2} [Fossils and Archeology Revival] (fossilsarcheology-7.3.2.jar) 
	UCHIJ	GardenContainers{1.7.10-1.7.0} [Garden Containers] (GardenStuff-1.7.10-1.7.0.jar) 
	UCHIJ	GardenCore{1.7.10-1.7.0} [Garden Core] (GardenStuff-1.7.10-1.7.0.jar) 
	UCHIJ	GardenStuff{1.7.10-1.7.0} [Garden Stuff] (GardenStuff-1.7.10-1.7.0.jar) 
	UCHIJ	GardenTrees{1.7.10-1.7.0} [Garden Trees] (GardenStuff-1.7.10-1.7.0.jar) 
	UCHIJ	Growthcraft{1.7.10-2.6.3} [Growthcraft] (growthcraft-1.7.10-2.6.3-complete.jar) 
	UCHIJ	Growthcraft|Cellar{1.7.10-2.6.3} [Growthcraft Cellar] (growthcraft-1.7.10-2.6.3-complete.jar) 
	UCHIJ	Growthcraft|Apples{1.7.10-2.6.3} [Growthcraft Apples] (growthcraft-1.7.10-2.6.3-complete.jar) 
	UCHIJ	Growthcraft|Bamboo{1.7.10-2.6.3} [Growthcraft Bamboo] (growthcraft-1.7.10-2.6.3-complete.jar) 
	UCHIJ	Growthcraft|Bees{1.7.10-2.6.3} [Growthcraft Bees] (growthcraft-1.7.10-2.6.3-complete.jar) 
	UCHIJ	Growthcraft|Fishtrap{1.7.10-2.6.3} [Growthcraft Fishtrap] (growthcraft-1.7.10-2.6.3-complete.jar) 
	UCHIJ	Growthcraft|Grapes{1.7.10-2.6.3} [Growthcraft Grapes] (growthcraft-1.7.10-2.6.3-complete.jar) 
	UCHIJ	Growthcraft|Hops{1.7.10-2.6.3} [Growthcraft Hops] (growthcraft-1.7.10-2.6.3-complete.jar) 
	UCHIJ	Growthcraft|Milk{1.7.10-2.6.3} [Growthcraft Milk] (growthcraft-1.7.10-2.6.3-complete.jar) 
	UCHIJ	Growthcraft|Rice{1.7.10-2.6.3} [Growthcraft Rice] (growthcraft-1.7.10-2.6.3-complete.jar) 
	UCHIJ	hamsterrific{0.2.0} [Hamsterrific] (Hamsterrific-0.2.0.jar.zip) 
	UCHIJ	icecreamcreepers{1.1.0a} [Icecream Sandwich Creeper Mod] (IceCreamSandwichCreeperModv1.1.0a 1.7.10.jar) 
	UCHIJ	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) 
	UCHIJ	jrfwalls{v1.7.10-00.01.05 Beta} [Uncle Jeff's Walls Mod] (jrfwalls-1.7.10-00.01.05.jar) 
	UCHIJ	LunatriusCore{1.1.2.21} [LunatriusCore] (LunatriusCore-1.7.10-1.1.2.21-universal.jar) 
	UCHIJ	lycanitesmobs{1.13.0.5 - MC 1.7.10} [Lycanites Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UCHIJ	arcticmobs{1.13.0.5 - MC 1.7.10} [Lycanites Arctic Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UCHIJ	demonmobs{1.13.0.5 - MC 1.7.10} [Lycanites Demon Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UCHIJ	desertmobs{1.13.0.5 - MC 1.7.10} [Lycanites Desert Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UCHIJ	forestmobs{1.13.0.5 - MC 1.7.10} [Lycanites Forest Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UCHIJ	freshwatermobs{1.13.0.5 - MC 1.7.10} [Lycanites Freshwater Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UCHIJ	infernomobs{1.13.0.5 - MC 1.7.10} [Lycanites Inferno Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UCHIJ	junglemobs{1.13.0.5 - MC 1.7.10} [Lycanites Jungle Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UCHIJ	mountainmobs{1.13.0.5 - MC 1.7.10} [Lycanites Mountain Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UCHIJ	plainsmobs{1.13.0.5 - MC 1.7.10} [Lycanites Plains Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UCHIJ	saltwatermobs{1.13.0.5 - MC 1.7.10} [Lycanites Saltwater Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UCHIJ	shadowmobs{1.13.0.5 - MC 1.7.10} [Lycanites Shadow Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UCHIJ	swampmobs{1.13.0.5 - MC 1.7.10} [Lycanites Swamp Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UCHIJ	MagicBees{2.4.3} [Magic Bees] (magicbees-1.7.10-2.4.3.jar) 
	UCHIJ	malisiscore{1.7.10-0.14.3} [MalisisCore] (malisiscore-1.7.10-0.14.3.jar) 
	UCHIJ	malisisdoors{1.7.10-1.13.2} [Malisis' Doors] (malisisdoors-1.7.10-1.13.2.jar) 
	UCHIJ	Mariculture{1.7.10-1.2.4.2a} [Mariculture] (Mariculture-Deluxe-1.7.10-1.2.4.2a.jar) 
	UCHIJ	MariTech{1.0} [Marine Technlogy] (Mariculture-Deluxe-1.7.10-1.2.4.2a.jar) 
	UCHIJ	RadixCore{2.1.3} [RadixCore] (RadixCore-1.7.10-2.1.3-universal.jar) 
	UCHIJ	MCA{1.7.10-5.2.2} [Minecraft Comes Alive] (MCA-1.7.10-5.2.2-universal.jar) 
	UCHIJ	thinknoodlesmod{1.0.12} [Thinknoodles mod] (minions-1.7.10-1.0.12.jar) 
	UCHIJ	Mo' Shiz{1.62.2} [Mo' Shiz] (Mo' Shiz v1.62.2.jar) 
	UCHIJ	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCHIJ	MoarSigns{1.2.4} [MoarSigns] (MoarSigns-1.7.10-1.2.4.jar) 
	UCHIJ	mochickens{1.6.2} [Mo Chickens] (MoChickens-1.7.10-1.6.2.jar) 
	UCHIJ	MoreBows2{1.2} [More Bows 2] (MoreBows2-1.2.jar) 
	UCHIJ	moreplayermodels{1.7.10b} [MorePlayerModels] (MorePlayerModels_1.7.10b.jar) 
	UCHIJ	cfm{3.4.8} [§9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.4.8(1.7.10).jar) 
	UCHIJ	mwaw{1.7.10-0.0.7} [Elemental Witch Mod] (mwaw-0.0.7-1.7.10.jar) 
	UCHIJ	Oceancraft{1.4.1} [Oceancraft] (Oceancraft-1.4.1.jar) 
	UCHIJ	harvestcraft{1.7.10j} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10Lb.jar) 
	UCHIJ	RidiculousWorld{0.1} [Ridiculous World] (Ridiculous World-0.4.jar) 
	UCHIJ	corerm{1.0c} [RikMuld's Core] (RikMuldsCore_1.0c.jar) 
	UCHIJ	Schematica{1.7.6.131} [Schematica] (Schematica-1.7.10-1.7.6.131-universal.jar) 
	UCHIJ	simplefluidtanks{1.7.10-1.2.0.5} [Simple Fluid Tanks] (simplefluidtanks-1.7.10-1.2.0.5.jar) 
	UCHIJ	stacywolves{1.0.7-1.7.10} [Stacy's Wolves Mod] (Stacy'sWolvesMod-1.7.10-1.0.12.jar) 
	UCHIJ	StorageDrawers{1.7.10-1.9.8} [Storage Drawers] (StorageDrawers-1.7.10-1.9.8.jar) 
	UCHIJ	StorageDrawersForestry{1.7.10-1.1.2} [Storage Drawers: Forestry Pack] (StorageDrawers-Forestry-1.7.10-1.1.2.jar) 
	UCHIJ	StorageDrawersMisc{1.7.10-1.1.2} [Storage Drawers: Misc Pack] (StorageDrawers-Misc-1.7.10-1.1.2.jar) 
	UCHIJ	StorageDrawersNatura{1.7.10-1.1.1} [Storage Drawers: Natura Pack] (StorageDrawers-Natura-1.7.10-1.1.1.jar) 
	UCHIJ	StuffedAnimals{1.7.10v1} [Stuffed Animals] (Stuffed Animals-1.7.10v1.jar) 
	UCHIJ	camping{2.1g} [The Camping Mod 2] (TheCampingMod_2.1g.jar) 
	UCHIJ	tropicraft{v6.0.5} [Tropicraft] (tropicraft-6.0.5.jar) 
	UCHIE	universalcoins{1.7.10-1.7.3} [Universal Coins] (UniversalCoins-1.7.10-1.7.3.jar) 
	UCHIJ	worldedit{6.0-beta-01} [WorldEdit] (worldedit-forge-mc1.7.10-6.0-beta-01.jar) 
	UCHIJ	XaeroMinimap{1.10.5} [Xaero's Minimap] (Xaeros_Minimap_1.10.5_Forge_1.7.10.jar) 
	UCHIJ	zapapples{1.7.10-2.4.1beta} [Zap Apples] (zapapples-1.7.10-2.5beta.jar) 
	GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.4358' Renderer: 'Intel(R) HD Graphics 4000'
	Mantle Environment: Environment healthy.
	CoFHCore: -[1.7.10]3.1.2-325
	Chisel: Errors like "[FML]: Unable to lookup ..." are NOT the cause of this crash. You can safely ignore these errors. And update forge while you're at it.
	Launched Version: 1.7.10-Forge10.13.4.1614-1.7.10
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics 4000 GL version 4.0.0 - Build 10.18.10.4358, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by spannerman79** [comment]
Run only the mod itself - nothing else before submitting issues.

**Comment by notabadminer** [comment]
this might be fixed with the 1.7.10-1.7.4 release. Test and update. Thanks
